apiVersion: v1
kind: Service
metadata:
   name: person
   labels:
      app: person
spec:
   type: NodePort
   ports:
   -  port: 8080
      name: http
   selector:
      app: person
---
apiVersion: apps/v1
kind: Deployment #对象类型
metadata:
   name: person-v1 #名称
   labels:
      app: person #标注
      version: v1 
spec:
   replicas: 2 #运行容器的副本数，修改这里可以快速修改分布式节点数量
   selector:
      matchLabels:
         app: person
         version: v1
   template:
      metadata:
         labels:
            app: person
            version: v1
      spec:
         containers: #docker容器的配置
         -  name: person
            image: jingjunlongsap/personservice:1.0 # pull镜像的地址 ip:prot/dir/images:tag
            imagePullPolicy: Always #pull镜像时机，
            ports:
            -  containerPort: 8080 #容器对外开放端口
---
apiVersion: apps/v1
kind: Deployment #对象类型
metadata:
   name: person-v2 #名称
   labels:
      app: person #标注
      version: v2 
spec:
   replicas: 2 #运行容器的副本数，修改这里可以快速修改分布式节点数量
   selector:
      matchLabels:
         app: person
         version: v2
   template:
      metadata:
         labels:
            app: person
            version: v2
      spec:
         containers: #docker容器的配置
         -  name: person
            image: jingjunlongsap/personservice:2.0 # pull镜像的地址 ip:prot/dir/images:tag
            imagePullPolicy: Always #pull镜像时机，
            ports:
            -  containerPort: 8080 #容器对外开放端口